### ISSUE TITLE
Code and Documentation

### ISSUE THREAD

**Issue by ghost** [SirisAvishek/Attention_Shift_Ranks#1]
@SirisAvishek Greetings,
- when is expected to release the code and documentation
- is there a limit to the number of objects that i want to rank?

**Comment by SirisAvishek** [comment]
@deepseek 

- Code, Data and Documentation are going through final preparation and checking. They will be released at the latest within a couple of days.
- Our current model aims to rank a maximum of 5 objects. You may wish to modify code to change to a limit of your choice.

**Comment by ghost** [comment]
Thanks
