### ISSUE TITLE
Predict The Sequence of Dialog in Comic Books

### ISSUE THREAD

**Issue by ghost** [SirisAvishek/Attention_Shift_Ranks#2]
@SirisAvishek 
Thanks for your hard work!

Take this example, i want to predict the order of the dialog in a comic book, basically telling which dialog box is 1st, which is 2nd, 3rd, etc...

- Can your code be trained to solve such task. wont the dialog boxes all look the same to it
- Can it be trained to predict 40+ dialog boxes in a single page. and at what computation cost.
- **Can it generalize on unseen images**. Will it really understand the visual context since most dialog boxes look the same.

![demo](https://user-images.githubusercontent.com/49877135/84791600-83234400-affb-11ea-9a38-9d34285bcacd.gif)

**Comment by SirisAvishek** [comment]
@deepseek 

I think that our saliency rank model will not fair too well with your example task. As you mention, the dialog boxes provide quite little differences in visual appearance, which would make it difficult for the model to rank them. Comic dialog reading is generally read in a certain order. However, the reading sequence may not be apparent in dynamic comic art styles. In this case, the sequence would be judged by multiple factors - which includes understanding of the visuals and story. 

I think you would need to create a more tailor made model for comic dialog read sequence suggestion. For example, you would need to provide information about each panel for a given page - visual and possible sequence order. Maybe incorporate rules, for instance, read top-to-bottom and specific types of text are read in some order (e.g. narration, speech, type of bubble shape). Additionally, the model could improve by understanding the visual and high-level context (story/speech/narration) in a temporal manner.

**Comment by ghost** [comment]
@SirisAvishek 
will this solve the task:
- represent the dialog as a gradient color.
- then creating a mask of the dialog from the gradient color.

-does your code see only instance segments, or can i represent the dialog in some form of color and gradient.

**Comment by SirisAvishek** [comment]
@deepseek 

Do you mean to represent each dialog bubble a specific solid colour from a gradient, which the gradient would then serve as the sequence order? 
Can you explain a bit further of how you would give colour to the dialog?

Our model work from object proposals and generate instance segmentation of a set of objects only. 
You may first want to try training a model to detect and segment dialog, then work from there.

**Comment by ghost** [comment]
Note that: I already have the dialog detected and have it's coordinates.

- I would choose some form of gradient, whether it's a color of pattern gradient.
- This gradient may look chaotic, but if you take even a small patch from it, you can tell it's exact location in the image. it's like the gradient contains the x+y coordinates at any patch point.

- Then i will mask my dialog within that gradient, and leave everything else as black.

Though, for training can i input gradient masks, or i can only input a single color single channel mask?

**Comment by SirisAvishek** [comment]
@deepseek 

If you mean to input gradient masks in our model, then you would need to modify the model to take gradient masks as input.
